name: ci

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: stevenmassaro/cuofco-mortgage-rate-check
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
          readme_file: 'README.md'
      - name: Determine alpine version
        id: version
        run: echo "VERSION=$(head Dockerfile -n 1 | cut -d ':' -f2 | cut -d " " -f1)" >> $GITHUB_OUTPUT
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests in docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          context: .
          target: test
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          context: .
          target: production
          tags: |
            stevenmassaro/cuofco-mortgage-rate-check:latest
            stevenmassaro/cuofco-mortgage-rate-check:${{ steps.version.outputs.VERSION }}